"""empty message

Revision ID: 644791b62da1
Revises: 834b1a697901
Create Date: 2022-12-05 23:37:19.519635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644791b62da1'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
